### ISSUE TITLE
Hardware - TODO

### ISSUE THREAD

**Issue by simonantonio** [nullydragon/WirelessRelay#1]
Change header terminals to larger 2.54mm pitch, remove the common pin from every channel, instead only have a single common per header row.

Verify diode direction.

Rework indicator led's to be inverted from current function

**Comment by nullydragon** [comment]
PCB has been fixed,
Diode indicators are now correct, 
Headers have been resized to 2.54mm pitch screw terminals
Added ESP8266-01 footer,
Added protection fuse (auto motive type holder, suggested 1Amp max)
Tweaked ESP8266-07 layout (now back only)
Won't fix LED functionality
